# Generated by Django 4.0 on 2022-01-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='desitnation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
